### ISSUE TITLE
Allow setting the OkHttpClient in OkHttpWebSocketTransport after initial construction

### ISSUE THREAD

**Issue by nathklei** [cometd/cometd#1048]
Use case: I would like to reset some state in the OkHttpClient backing my OkHttpWebSocketTransport if I encounter a transport failure at runtime. Specifically, I would like to reset the SSLSocketFactory backing the OkHttpClient (to pick up new SSL configuration).

The "best" way I can see to implement this is to listen for transport failures, and if the transport is an instance of OkHttpWebSocketTransport, reset its underlying client with fresh configuration.

I'm also open to other options for accomplishing the same thing.

If exposing a mutator for the OkHttpClient in OkHttpWebSocketTransport sounds reasonable, I'm happy to contribute the change. 

Thanks!

**Comment by nathklei** [comment]
A separate approach might be to fully swap in a new OkHttpWebSocketTransport from scratch with the new OkHttpClient, but I don't see a way to do that.  I also would be worried about hot swapping entire transports in the general case if they have some internal state / lifecycle.

**Comment by sbordet** [comment]
@nathklei typically it's the application that passes an instance of `OkHttpClient` to the CometD transport, so the application has a reference to it and can do whatever it wants with it.

CometD can expose a getter for `OkHttpClient`.

How thread safe is to change the `OkHttpClient` state would be up to the application.

If the getter is enough for you, and you want to provide a PR, be my guest 👍🏼

**Comment by nathklei** [comment]
Hey @sbordet - unfortunately the `OkHttpClient` itself is not mutable, so a getter won't be enough, I think we'll need a mutator. Atomically swapping in the OkHttpClient should be safe on transport failure, but I'll work to confirm.

**Comment by sbordet** [comment]
@nathklei but if you plan to swap on transport failure, can't you just re-create the whole `BayeuxClient` and re-handshake?

I ask because I would expect that a fresh new `OkHttpClient` won't have the CometD cookie of the previous instance, so attempts to communicate will likely result in a re-handshake.

And if you need to re-handshake anyway, then re-creating the whole `BayeuxClient` may be simpler.

**Comment by nathklei** [comment]
I haven't dug into it, but I assumed that transport failures can happen for a wide variety of reasons, including losing network connection intermittently - in those cases I was hoping that the internal re-connect mechanisms of BayeuxClient would allow me to automatically connect to an existing ServerSession on the server, without me needing to re-subscribe, etc. For that reason I was hoping I could just adjust the transport so that next reconnect I use a fresh SSLSocketFactory in the OkHttpClient - if I just swap in the BayeuxClient, I'd create a new client/server session possibly.

**Comment by sbordet** [comment]
@nathklei that feels really difficult.

Depending on the application, CometD is typically seen as a "transport" layer that's always working.

Human interactions, timers, etc. just use `BayeuxClient` at any time asynchronously with anything that comes from the server, also asynchronously.

Swapping the transport means grabbing a global lock and forcing everything to stop until the swap is done.
Some application may be built in a way that they already serialize all accesses to `BayeuxClient` so things may be a little simpler, but not much (you still have asynchronous communication from the server).

HTTP transport rely on the CometD cookie, which is handled by `BayeuxClient`, so swapping the transport is definitely simpler.

WebSocket transports should not trust new connections that present the same `clientId`, see https://docs.cometd.org/current/reference/#_security_xss and parameter `requireHandshakePerConnection`.

Perhaps you should explain what your problem is in more details.
The solution of "swapping `OkHttpClient`" may or may not work, but perhaps there are better solutions.

Did you try Jetty's WebSocket transport along with the fact that you can reload Jetty's `SslContextFactory`?
Maybe that's enough for you.

**Comment by nathklei** [comment]
Hey @sbordet - thanks for the detailed reply.  I agree that this is a tricky/difficult situation. I also was not aware of requireHandshakePerConnection, which seems to be false by default, but seems to be more secure.

This request came up due to a recent issue I encountered where my client was unable to connect for an extended period of time until restarted - I unfortunately did not get exact logs indicating that there was an SSL handshake issue, but I suspect that to be the case based on other things going on in the system. My thinking is that allowing my application to swap in a new SSLSocketFactory based on a (possibly updated) trust store would remove some specific issues.

I'd prefer to not use Jetty's WebSocket transport on my client, as my clients already have OkHttp and I'd rather not bundle additional jars across my ecosystem - but if it's possible in Jetty, I could look into it.

Do you have a good example of swapping out an entire BayeuxClient in the event of certain types of transport failures? I don't on the surface see a way to accomplish this given that the transport layers are detected within the client, but I might be missing some callbacks/patterns to use.

**Comment by sbordet** [comment]
@nathklei in general, there is no "safe" way to swap a `BayeuxClient`.

The CometD implementation can't really do it, as it would have to grab a global lock for every operation, which would be a performance hit.

Applications, OTOH, may know a little better whether they are sending messages or not.
If an application knows that it's not sending messages, and it received a WebSocket transport failure, and it has no other asynchronous activities going on that may access the `BayeuxClient` instance, then it may swap it.

However, seems to me that you're not 100% sure of the issue, so I would delay implementing any "swap `BayeuxClient`" solution until you have a firm grip on what the problem really is.
Would not be the first time that I've seen problems fixed by replacing a faulty network switch, for example.

**Comment by nathklei** [comment]
Thanks @sbordet  - I'm running some tests on my end to confirm the issue before I move forward with any more invasive changes. Appreciate you iterating with me!

**Comment by sbordet** [comment]
@nathklei feel we can close this?

**Comment by nathklei** [comment]
Yeah - I'll close this for now. It hasn't come up recently.
