### ISSUE TITLE
Self interference in Oort from 2 independent CometD instances 

### ISSUE THREAD

**Issue by zenbones** [cometd/cometd#1052]
I'm not sure this is a ticket, so take this with a grain of salt, but as you asked from our last conversation...

I have a single web application server, in our case grizzly, hosting 2 independent instance of BayeuxServerImpl, each of which is injected into one of two independent CometDServlet instances, hosted on two different URLs on the singular grizzly instance. They have very different security logic implemented in two different SecurityPolicy implementations, as well as other differences, as our reason for this setup (old and new if you will). Everything works fine as far as we can tell. Both instances of CometD have websocket, long polling and callback polling installed.

I added Oort to just the newer CometD setup. If I limit that newer setup to long polling only, Oort works as expected. If I turn on websockets as well then Oort fails. It fails because the HandshakeListener in OortMembership never receives messages with the 'org.cometd.oort' sub-attribute of 'ext'. They have the 'ack' attribute only. If I turn off websocket, then the first handshake attempts websocket and fails, while the next handshake uses long polling, has the 'org.comet.oort' information and succeeds. If I turn off the older CometD implementation, so I'm running only the newer implementation with Oort, then everything works fine even with websockets on.

This might by a problem in the way websockets configure themselves in CometD, it could be a problem in Tyrus (the websocket implementation we're using in Grizzly), or it could be a problem in the Nginx layer we use as a reverse proxy to route traffic to our various subsystems. I'll note that until I installed Oort we've ad no issue with using websockets, and the client connections over websocket seem to go to the correct CometD instance every time, routing properly through Nginx. The only problem we see is in the HandshakeListener in OortMembership.

I know this is a corner case. My current plan will be to create a new independent server for each CometD instance, i.e. run them on independent instances of Grizzly, on two different ports. That will probably work. It may be more sane overall. But, if you had some extra time (as we all do), and wanted to take a look at this problem, I am also available to help.

**Comment by sbordet** [comment]
Your use case is a rare one, and not supported out of the box (but still doable).

What the default CometD initialization does (via `CometDServlet`) is to create a `BayeuxServer` instance and store it as a `ServletContext` attribute.

This is because the default is that a single web application does not need more than one `BayeuxServer` instance and so we store it in the `ServletContext` so that's easily accessible from the web application.

Your case is that you have 1 web application but you want 2 `BayeuxServer` instances.
What I think you see is that Oort is configured with one `BayeuxServer` instance, but messages are processed by the other `BayeuxServer` instance, and that's why you don't see the expected Oort extensions installed.
The fact that you see some behavior in one case (only long-polling) could be due to timings and ordering and possibly just by chance.

 If you really, really need 2 `BayeuxServer` instances, I recommend that you explicitly create them and explicitly pass the one you want to `Oort`, as `OortConfigServlet` will take the one in the `ServletContext`.

Alternatively, you can deploy 2 web applications, each with just one `BayeuxServer` instance and different URIs (you don't need different servers on different ports -- although that would work too).

We test heavily CometD with Jetty and we know it's stable and scales really really well because we have large customers using CometD on Jetty.
CometD on Grizzly/Tyrus should work but we don't know how well.

Also, make sure you have read this: https://docs.cometd.org/current5/reference/#_java_oort.
The Nginx you have in front must be sticky.

**Comment by joakime** [comment]
With nginx, make sure you have a sane (for websocket) proxy timeout, and are not using the default (of 60 seconds).

Might want to make sure your nginx idle timeout is larger than your grizzly/tyrus idle timeouts (grizzly and tyrus tracks idle timeout separately).

Example of a 24 hour idle timeout.

```
proxy_read_timeout 86400s;
proxy_send_timeout 86400s;
```

**Comment by zenbones** [comment]
The BayeuxServerImpl instances are created via Spring and injected with a ServletContextListener instance which are themselves injected with the BayeuxServerImpl.

```
  @Override
  public void contextInitialized (ServletContextEvent servletContextEvent) {

    servletContextEvent.getServletContext().setAttribute(BayeuxServer.ATTRIBUTE, bayeuxServer);
    cometDServer.setOption(ServletContext.class.getName(), servletContextEvent.getServletContext());

    try {
      bayeux.start();
    } catch (Exception exception) {
      throw new RuntimeException(exception);
    }
  }
```

But, now that you've pointed it out, the fact that the right CometD instance ends up with the right BayeuxServer instance via the correct ServletContextListener may be an artifact of the order in which the spring files are loaded and how we construct Grizzly (and yes, we start spring which constructs and injects Grizzly as part of our overall application). The two BayeuxServerImpls have very different authentication logic, so I know that the correct BayeuxServer ands up with the correct CometD instance every time, but looking at it now, that was probably luck rather than planning. However, it is true. And, in fact, the correct BayeuxServerImpl ends up with the Oort servlet as well, every time, via the same instantiation ordering. And I know this is true because the SecurityPolicy in effect is the one from the correct BayeuxerverImpl, as is the logging and everything else, every time. Maybe not a well-planned system, but a working one. And likewise the long polling working is absolutely consistent, as is the websocket failure.

All that said, this is not a good system and I'll fix that first. If that fixes the problem I'd be happy. Thank you.

**Comment by zenbones** [comment]
After changing our spring initialized web app server to allow us to initialize two different web app contexts, and attaching the cometd installations to the two different contexts, everything works correctly with websockets as well as long polling. Thank you once again for your most helpful help.
