### ISSUE TITLE
Implement an API to force a ping on `/meta/connect`

### ISSUE THREAD

**Issue by boris-petrov** [cometd/cometd#1900]
**CometD version(s)**
6.x

**Java version & vendor** `(use: java -version)`
N/A

**Question**
I'm trying to test the reconnect functionality in my app. That is, I open the page, stop the internet, check that there is a notification, then start the internet and check that all works fine. I depend on `/meta/connect` for that. The problem is that the ping is every 30 seconds or so. This means that my test has to wait for 30 seconds for the notification to be shown.

Is it possible to have an API to force a ping so that this process is immediate?

**Comment by sbordet** [comment]
CometD uses `maxNetworkDelay` to detect whether a `/meta/connect` is lost, so on the client the max time to detect a loss is `timeout+maxNetworkDelay`.
You can configure both in your tests to smaller values than the default.

When the connectivity is lost, CometD uses a retry mechanism that can be configured.

When using the Java client, you have `BayeuxClient.setBackOffStrategy()` to control the retry mechanism.
By default, the `Linear` implementation is used, so the 1st retry happens immediately, the 2nd retry after one period, the 3rd retry after two periods, etc.
There is a `Constant` implementation available too.

The lack of an explicit API to force a `/meta/connect` is by design, since it is the key mechanism for the heartbeat, and having an explicit API that applications can call will likely result in messing up the whole mechanism.

**Comment by boris-petrov** [comment]
Thanks for the detailed answer! What is `timeout` you're talking about? There is no such configuration in the documentation. I'm talking about the JS client.

**Comment by sbordet** [comment]
The `timeout` parameter is the CometD `/meta/connect` `timeout`: https://docs.cometd.org/current8/reference/#_java_server_configuration_transports

The JS client does not have a pluggable backoff strategy (has an hardcoded linear strategy), but you can configure the `backoffIncrement` to small values, so that it almost behaves like a constant strategy.

**Comment by boris-petrov** [comment]
Ah, thanks, I was looking at the JS settings. A final question - is it possible to change these settings dynamically on the backend? I want to start with the default `timeout`, change it to a small value for one particular test and then revert it to the original value - all without restarting the server. Is that possible?

**Comment by sbordet** [comment]
You can change the `timeout` value on a per-session basis, via `ServerSession.setTimeout(...)`.

This is best done in a handshake listener, before any `/meta/connect` is sent/received, via `BayeuxServer.getChannel(Channel.META_HANDSHAKE).addListener(...)`.

**Comment by boris-petrov** [comment]
Thank you for the help!
