### ISSUE TITLE
spec reference to RFC2396 for channelnames contradicts BNF and should be removed or clarified

### ISSUE THREAD

**Issue by squiddle** [cometd/cometd#605]
I might be misreading the specification but the channel name should allow the percent symbol as part of percent escaping (actually it should probably unescape it).

The Spec http://docs.cometd.org/3/reference/#_channels says the channel is following RFC2396 path component.

Looking at the RFC https://tools.ietf.org/html/rfc3986#section-3.3
`escaped` characters are allowed in path components. 

cometd 3.0.5 java

**Comment by sbordet** [comment]
The [Bayeux Specification](http://docs.cometd.org/3/reference/#_bayeux) explicits the BNF in [this section](http://docs.cometd.org/3/reference/#_common_elements), and the `%` character is not among those you can use in a channel name.

We should probably remove the references to RFC 2396, since the BNF grammar is in the Bayeux Specification itself.

Do you have a case where you want to have a channel with a `%` or with some kind of URL escaping ?

**Comment by squiddle** [comment]
oh i got confused by the reference to the RFC. I think the reference should be removed then.

the use case is, we are having special characters in the channel (in this case a '/' which should not demarcate a bayeux channel path segment) and i saw the reference to RFC 2396 and thought regular percent escaping will solve my problem.

sorry for missing the BNF on top :/

i changed the issue title to reflect my mistake

**Comment by sbordet** [comment]
Moved to cometd/cometd-documentation#5.
