### ISSUE TITLE
Support CommonJS/ES6 modules definition

### ISSUE THREAD

**Issue by ghoullier** [cometd/cometd#626]
Hi Guys!

Current CometD JS client use global namespace to define modules.

New JavaScript version embed module definition syntax very closed to CommonJS

I've found a [project](https://github.com/craigdallimore/cometd-cjs) (seems no longer maintened) which implements CommonJS.

```js
// ES6 syntax
import { CometD, LongPollingTransport, Transport } from 'cometd';
```
Is the roadmap Cometd will include the integration of CommonJS/ES6?

**Comment by sbordet** [comment]
The current CometD JS client does use global namespaces, but it is also able to use the AMD format, so CommonJS is already supported.

There are examples in the demos that use RequireJS and Dojo/jQuery with AMD modules. 

The `import` syntax seems to be only support by transpilers, and not by browsers.
Do you have any authoritative source about what browser implements `import` ?

Is the support for AMD modules, CommonJS and RequireJS enough for you ?

**Comment by ghoullier** [comment]
There are only AMD examples I've not found CommonJS examples.

I use browserify to bundle my application and CommonJS modules must define module.exports to be loaded as valid dependency.

On the *import* syntax, I'm still looking for authoritative source, but there is an opened issue in [kangax compat-table projet](https://github.com/kangax/compat-table/issues/316) to test browser support

**Comment by ghoullier** [comment]
@sbordet Sources about EcmaScript Module loader
- https://github.com/whatwg/loader
- http://whatwg.github.io/loader/

**Comment by sbordet** [comment]
Is Dojo or jQuery or Angular supporting CommonJS ? Who is using it ?

**Comment by ghoullier** [comment]
Angular support CommonJS since [v1.3](https://github.com/angular/angular.js/pull/10732)
React support CommonJS since begining https://facebook.github.io/react/docs/getting-started.html

**Comment by ghoullier** [comment]
Hi!!

I'm preparing a Pull Request to implement [UMD](https://github.com/umdjs/umd) which allow Global, AMD and CommonJS module definition support

**Comment by sbordet** [comment]
For the life of me, I don't understand CommonJS at all.

Can you please explain to me how is one supposed to use it, with a simple example application ?

All the examples I could find online talk about using CommonJS on the server (which is not what the CometD JavaScript library is about), or require some preprocessing step which is not needed with any other solution, [quoting](http://know.cujojs.com/tutorials/modules/authoring-cjs-modules):

> However, browsers can't consume them directly because browsers don't create the CommonJS scoped variables. Performance also suffers dramatically when browsers must load dozens or hundreds of modules in any non-trivial application.

**Comment by sbordet** [comment]
@ghoullier I am close to give up on this issue.

I cannot find any recent resource that shows a full fledged commonjs example, or how I would even use commonjs in a browser.

Furthermore, commonjs seems to be "wrapped" by loaders into AMD format, which CometD already supports. As such there is no need of commonjs support because files written in that way will be loaded and wrapped automatically in AMD format.

Unless there is a real example of why this is needed, I don't think it will be implemented.
While your PR may be ok, I lack the use case, tests and examples to accept it. 

CommonJS seems dead to me on the browser.

I would like a full fledged example to understand how commonjs actually works: what files to include in the `html` resource, how to bootstrap the commonjs loader, and an idiomatic commonjs application.

Thanks !

**Comment by ghoullier** [comment]
Hi!

This is a complete guide to [Use CommonJS with Browserify](https://github.com/substack/browserify-handbook/blob/master/readme.markdown)

This [other example](http://www.leanpanda.com/blog/2015/06/28/amd-requirejs-commonjs-browserify/) explains how to support CommonJS/AMD modules.

Like AMD, CommonJS is not natively supported in browsers, developpers must use a bundler (Browserify, Webpack, Rollup, ...)  to support this format.

I'll try to push this week a project on my account to show you how commonjs actually works.

**Comment by sbordet** [comment]
If the goal is only to be able to consume CometD with Browserify and your other modules written using CommonJS, this is already possible because Browserify supports AMD.
If this is the use case, then I see no need to support CommonJS _inside_ of CometD: just do the right thing at build time with Browserify.

Otherwise, I would like to see how a CommonJS module is loaded _directly_ into the browser, which would be the only reason to support CommonJS inside CometD.
But for what I searched, there is no such example, or it is heavily discouraged, or it is really old (like years old).

I need a very strong argument.

**Comment by ghoullier** [comment]
Current AMD support just exposes an existing global variable _org.cometd_ instead of individuals modules.

You still must include cometd files in correct order to obtain a working project, it's clearly not the way module loading should work.

**Comment by sbordet** [comment]
@ghoullier exposing the global variable is required for backwards compatibility. The AMD support works without referring to the global variable, so module loading works as expected.

Going back to CommonJS, if tools can handle mixed AMD _and_ CommonJS files, then we are good already.

Otherwise I need a sample application that shows me how to bootstrap and load modules using CommonJS _without_ a build step.

Thanks !

**Comment by ghoullier** [comment]
UMD automatically chooses the correct module definition. In AMD context,  no global variables are created. With the current implementation, a global variable is always created.

CommonJS need a compile step so I can't give you this example :-)

**Comment by sbordet** [comment]
@ghoullier the global variable is created on purpose for backwards compatibility.

If CommonJS requires a build step, and build tools supports AMD, then are we done ?
I am asking because I don't know, but I see little reason to add something to CometD if there is no need to :)

Thanks !

**Comment by ghoullier** [comment]
I dont know if build tools supports mixed modules declarations (AMD and CommonJS). Moderns libs and frameworks like React and Angular support only ES6 and CommonJS.

**Comment by sbordet** [comment]
@ghoullier closing this as discussion is continuing on #649, please join us there.
