### ISSUE TITLE
Undefined values in _listeners channel arrays

### ISSUE THREAD

**Issue by chchrist** [cometd/cometd#654]
Hello,

I was doing some debugging and I found out that the _removeListener() does not remove the undefined array element after the subscription was deleted.
https://github.com/cometd/cometd/blob/master/cometd-javascript/common/src/main/js/org/cometd/CometD.js#L253

This has as a result that the length of a channel _listeners  array for example to be 14 when there are no subscriptions.

Is that on purpose?

**Comment by sbordet** [comment]
The idea is that if you add 2 subscriptions for the same channel, you want to be able to remove them.

After adding the 2 subscriptions, `_listeners` is:

```javascript
{ "/channel": [{ id: 0, ... }, { id: 1, ... }] }
```

The ids are generated using their position in the array.

The subscriptions are returned to the application, so it can remove them.
After removing the first subscription, `_listeners` is:

```javascript
{ "/channel": [ undefined , { id: 1, ... }] }
```

Note the initial element is `undefined`. This element at index 0 must remain because the second subscription is removed using its `id`. The array cannot be  `splice()`d.

What can be done is that if also the second subscription is removed, the array is `[ undefined, undefined ]`, so it can be replaced with the really empty array `[]`, but doing this will require additional housekeeping (need to keep the number of non-undefined elements in the array), so it was left it as it is now.

Any suggestion on a data structure that is more efficient, I am all ears.

The alternative could be to generate the ids externally (without relying on the array generating them) and then use this:

```javascript
{ "/channel": { "0": ..., "1": ... }
```

Then it would be possible to just delete the subscription with the right id.
I guess historically the data structure was much simpler, it evolved trying to keep the original design, but eventually became a bit complicated.

**Comment by chchrist** [comment]
Thank you for the reply. I will investigate if it is possible to replace the array with object keys

**Comment by sbordet** [comment]
You want to give it a try and prepare a pull request ? Otherwise I'll do it.
