### ISSUE TITLE
Memory Leak -  Flusher objects in FAILED state

### ISSUE THREAD

**Issue by kulinski94** [cometd/cometd#655]
We've been observing `OutOfMemoryException`s lately.  The heap dump shows that there are a number of `Flusher` objects in `FAILED` state.  One of those has a substantial number of elements in the _entries collection, causing the heap exhaustion.

I'm not familiar with neither CometD's nor Jetty's internals, but here's what I've been able to find:

Once a `Flusher` enters failed state there's no way it can exit it.

For the sake of experiment I've added `onCompleteFailure()` to `Flusher` class and verified that it's queue method is invoked even after it's been marked failed.

Looking at this code in `org.cometd.websocket.server.WebSocketTransport#send()`

``` java
wsSession.getAsyncRemote().sendText(data, new SendHandler()
{
    @Override
    public void onResult(SendResult result)
    {
        Throwable failure = result.getException();
        if (failure == null)
        {
            callback.succeeded();
        }
        else
        {
            handleException(wsSession, session, failure);
            callback.failed(failure);
        }
    }
});
```

it appears that failure is indeed expected.  Given that the callback is the `Flusher` object it's not hard to see how it can end up being in `FAILED` state.

The question is shouldn't `Flusher` override `onCompleteFailure()` ?  I've been experimenting with adding:

``` java
AbstractWebSocketScheduler.this.close(1011, x.toString());
```

and/or

``` java
if (_session != null)
    _session.disconnect()
```

and

``` java
_entries.clear()
```

but without much knowledge about CometD I'm not certain this is the right call. Any recommendations?

For the record we're using version 3.0.4, but the relevant code is the same in 3.0.9.

Best regards

**Comment by sbordet** [comment]
Sorry for the delay.

A `Flusher` instance is created for each connection. If the `Flusher` fails, it means that the connection has failed, and eventually connections should be closed and garbage collected, thus garbage collecting the `Flusher` too and all the messages in its queue. It should take at most one idle timeout to detect that the `Flusher` needs to be removed.

We can certainly improve the code to discard - rather than queuing - messages if the `Flusher` is failed.

However, you should get `OutOfMemoryError`s only in the case of a very long idle timeout, and a very high server message rate. Is that the case ?

Can you take a `Server.dump()` (via JMX, for example) when it fails ?
Can you attach the heap dump here ?

Thanks !

**Comment by sbordet** [comment]
I committed some fixes that improve on the CometD side by not queuing entries if the `Flusher` is already failed.

However, as I said, the `Flusher` instances should be garbage collected, so any additional information you may have from server dumps and heap dumps will help analyze this issue.

Thanks !

**Comment by sbordet** [comment]
Closing, no further comments. Please comment if it's still an issue.
