### ISSUE TITLE
angularjs 2 can use cometd ?

### ISSUE THREAD

**Issue by clp334264003** [cometd/cometd#657]
angularjs 2 can use cometd ?

**Comment by sbordet** [comment]
Have not tried that yet. CometD 3.1 is integrated with AngularJS 1.

**Comment by idinf2004** [comment]
I actually have the same question, I wonder if you have some tips about how to use cometd with AngularJS 2

**Comment by sbordet** [comment]
I have not tried yet. I would appreciate if someone can give it a try and report back.

**Comment by w0jcik** [comment]
We use it with Angular7.
If you use typescript you will want to also install @types/cometd (but it is currently missing some transport types).
Since cometd is commonJS module, you will need to set this in tsconfig.json:
    "esModuleInterop": true,

**Comment by sbordet** [comment]
@w0jcik thanks for reporting this.
Closing as apparently CometD is working with Angular > 1 without any further need.

**Comment by mkorkar** [comment]
Hi sbordet,
i have tried to use with angular 8 but useless so if you can provide example for this

**Comment by sbordet** [comment]
@mkorkar what's the problem? AFAIK, Angular > 1 does not require any specific integration so you can just use CometD as you like.

**Comment by mkorkar** [comment]
hi sbordet, glade to hear from you
finally i am able to make the project compile successfully but i used cometd-jquery code as found in 
the Demo [the primer->the maven way]
i use microservice architecture [i mean frontend not packaged with backend as in the demo ] and 
i am  able to deploy the spring boot backend code [cometd server side] on jetty [9.4] successfully 
but i hit in an exception that front can not establish handshake due to CORS exception
i tried alot but useless so, is it mandatory to wire them (frontend & backend) together ?
thanks in advance

**Comment by sbordet** [comment]
@mkorkar it's not mandatory to make front-end and back-end on the same host.
See https://docs.cometd.org/current4/reference/#_javascript_transports_cross_origin.

**Comment by mkorkar** [comment]
@sbordet ,
from the primer Demo i noticed that you used a [CrossOriginFilter] and since my backend is spring boot deployed in standalone jetty and based on your spring boot demo this is my class :
-----------------------------------------------------------------------------------
@SpringBootApplication
@EnableWebMvc
public class SpringBootWebSocketDemoApplication extends SpringBootServletInitializer implements ServletContextInitializer {

	@Override
	protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {
		return application.sources(SpringBootWebSocketDemoApplication.class);
	}


	public static void main(String[] args) {
		SpringApplication.run(SpringBootWebSocketDemoApplication.class, args);
	}

	@Override
	public void onStartup(ServletContext servletContext) throws ServletException {
		
		System.out.println("servletContext : "+servletContext); 
		ServletRegistration.Dynamic cometdServlet = servletContext.addServlet("cometd", AnnotationCometDServlet.class);
		cometdServlet.addMapping("/cometd/*");
		cometdServlet.setAsyncSupported(true);
		cometdServlet.setLoadOnStartup(1);
		cometdServlet.setInitParameter("services", HelloService.class.getName());
		cometdServlet.setInitParameter("ws.cometdURLMapping", "/cometd/*");
		
		
		FilterRegistration.Dynamic cometdFilter = servletContext.addFilter("cross-origin", CrossOriginFilter.class); 
		cometdFilter.addMappingForUrlPatterns(null, false, "/cometd/*");
	    cometdFilter.setInitParameter(ALLOWED_METHODS_PARAM, "GET,PUT,POST,OPTIONS,DELETE");
	    cometdFilter.setInitParameter(ALLOWED_ORIGINS_PARAM, "*");
	    cometdFilter.setInitParameter(ALLOWED_HEADERS_PARAM, "X-Requested-With,Content-Type,Accept,Origin,authorization");
	    cometdFilter.setInitParameter(ALLOW_CREDENTIALS_PARAM, "true");
	    cometdFilter.setInitParameter(EXPOSED_HEADERS_PARAM, "Content-Type,Authorization,X-Requested-With,Content-Length,Accept,Origin,Location,Accept-Content-Encoding");
		
	}
	
}

**Comment by mkorkar** [comment]
from the primer Demo i noticed that you used a [CrossOriginFilter] and since my backend is spring boot deployed in standalone jetty and based on your spring boot demo this is my class :
-----------------------------------------------------------------------------------------------------
@SpringBootApplication
@EnableWebMvc
public class SpringBootWebSocketDemoApplication extends SpringBootServletInitializer implements ServletContextInitializer {

@Override
protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {
	return application.sources(SpringBootWebSocketDemoApplication.class);
}
public static void main(String[] args) {
	SpringApplication.run(SpringBootWebSocketDemoApplication.class, args);
}

@Override
public void onStartup(ServletContext servletContext) throws ServletException {
	
	ServletRegistration.Dynamic cometdServlet = servletContext.addServlet("cometd", AnnotationCometDServlet.class);
	cometdServlet.addMapping("/cometd/*");
	cometdServlet.setAsyncSupported(true);
	cometdServlet.setLoadOnStartup(1);
	cometdServlet.setInitParameter("services", HelloService.class.getName());
	cometdServlet.setInitParameter("ws.cometdURLMapping", "/cometd/*");
	
	
	FilterRegistration.Dynamic cometdFilter = servletContext.addFilter("cross-origin", CrossOriginFilter.class); 
	cometdFilter.addMappingForUrlPatterns(null, false, "/cometd/*");
    cometdFilter.setInitParameter(ALLOWED_METHODS_PARAM, "GET,PUT,POST,OPTIONS,DELETE");
    cometdFilter.setInitParameter(ALLOWED_ORIGINS_PARAM, "*");
    cometdFilter.setInitParameter(ALLOWED_HEADERS_PARAM, "X-Requested-With,Content-Type,Accept,Origin,authorization");
    cometdFilter.setInitParameter(ALLOW_CREDENTIALS_PARAM, "true");
    cometdFilter.setInitParameter(EXPOSED_HEADERS_PARAM, "Content-Type,Authorization,X-Requested-With,Content-Length,Accept,Origin,Location,Accept-Content-Encoding");
	
}
}
-----------------------------------------------------------------------------------------
based on the above this filter not work and still the same issue [CORS] so is there any correct way to define the filter as i don't use XML Configuration

**Comment by sbordet** [comment]
Once you are adding the CORS filter, it should work.
If it does not, then please: A) open a new issue as this one is not relevant anymore and B) must give details of "filter not work" (like: what happens exactly? client DEBUG logs? server DEBUG logs?).
