### ISSUE TITLE
How to react in CometD if too many requests come to server? 

### ISSUE THREAD

**Issue by hepuyi** [cometd/cometd#692]
We are using CometD as framework to push messages from server side to client side in app. In doc https://docs.cometd.org/current/reference/#_configuring_code_bayeuxserver_code, there is one property "interval" to control reconnect(/meta/connect request) from client side, but this seems like static configuration for all such requests, it can not help if too many requests come to server at rumtime(not always), how to react on server side in CometD for such case? is there any other way to detect incoming request rate and update "interval" with bigger number on demand if many requests at peak time?

There is one issue in our app, we set 0 as "interval" value by default but too many /meta/connect requests came at some time, our app(only one server for example) was down afterwards and client sides got 402 for all such requests. We are looking for some general way to not let server down.

Thanks in advance!

**Comment by sbordet** [comment]
What server are you using, and what rate of requests/s are you talking ? I ask because I have been able to push CometD to many tens of thousands of requests/s, which often translates to hundreds of thousands of messages/s.

If you are above that, then it's an interesting case and we can discuss the details further.

If you are below that, then it's probably something else and more details are needed to understand what's going on.

What is the rate of events happening on the server for a particular session ? That will give an approximate rate for `/meta/connect` requests.

If you have a continuous flow of events on the server, then you probably want to read [this](https://webtide.com/cometd-message-flow-control-with-lazy-channels/) and [this](https://webtide.com/cometd-message-flow-control-with-listeners/) blogs.

In any case you need to describe in details, with numbers, what is your system doing, and we can follow from there.

**Comment by hepuyi** [comment]
We are using 5 CometD servers(working individually without clustered) to synchronize clients and servers with message delivery, and there is a load balance server to forward requests to the servers, when 2 or the servers were turned off manually(test case of performance), the other 3 servers would receive requests from the turned-off 2 servers as well(although invalid any more), the 402 rate is close to 7k which is a breaking point level and Longpoll reaches 13.1K per minutes for each server, this made the 3 servers down soon.

So I just summarized it as too many requests to single server and look for solution to let server alive without down.

**Comment by sbordet** [comment]
I'm not sure I understand.

If serverA goes down, serverB will receive a `/meta/connect` request to which it will reply with a CometD `402::unknown_client`, and the server will ask the client to re-handshake, so the client should now be connected to serverB.

If serverA had, say, 5000 clients connected, then serverB (and the other servers still alive) would receive a peak of traffic for all serverA clients that are trying to reconnect.

This has not much to do with CometD, it would happen for a normal website as well, and you can throttle requests to smooth out the peak of requests if you cannot sustain them.

13K requests/minute == 220 requests/s which is nothing for CometD to handle (as I said, it will start to be interesting at 50K requests/s), so I am surprised your servers went down.
Are these virtualized, super-small server instances that cannot cope with 200 requests/s ?

**Comment by sbordet** [comment]
Closing, as there was no further information.
