### ISSUE TITLE
Poor script reuse with Nashorn tests

### ISSUE THREAD

**Issue by szegedi** [cometd/cometd#741]
Example code from `JQueryTestProvider`:
```
        javaScript.evaluate(new URL(contextURL + "/jquery-3.2.1.js"));
        javaScript.evaluate(new URL(contextURL + "/js/cometd/cometd.js"));
        javaScript.evaluate(new URL(contextURL + "/js/jquery/jquery.cometd.js"));
```
Nashorn engines have an internal MRU code cache (by default, for 50 scripts) and when asked to evaluate code from a cached URL they'll reuse the cached bytecode, instead of recompiling it from source. Unfortunately, with both `JQueryTestProvider` and `DojoTestProvider`, you're loading these from a different `contextURL` (HTTP servers running on different ports), so it defeats the reuse mechanism. 

If you could restructure the tests to always load the fixed scripts from a fixed URL (similar to how [I did it](https://github.com/cometd/cometd/pull/740/files#diff-56602925964f96d7c469ab2605289fdaR188) for `/browser.js` in #740), I predict you'd drastically speed up test execution. Extracting various inline scripts in `provideCometD` (`cometd`, `original_transports`, `only_websocket`, etc.) into classpath resources and loading them from there would also help.

I'm reluctant to do this myself as I'm not sure about the implications: you might have a genuine semantic reason for the tests to pull them over HTTP; I'm just pointing out a place where Nashorn's code cache is defeated because of subtly differing URLs for the same scripts.

**Comment by sbordet** [comment]
I changed the relevant lines for both JQuery and Dojo, so that large scripts are loaded from the file system, rather than always changing URLs, so that the reuse mechanism can be leveraged now.

There was no particular semantic (I was not testing cross-domain restrictions that browsers impose on scripts), it was just me trying to simulate a webapp where those files are served by the server. 

The tests run pretty quickly now, but I hit the same 2 errors that you found in #740.
One of them is probably an unstable test, the other seems a Nashorn issue that I discuss in #742.

**Comment by sbordet** [comment]
Awesome improvements, tests run in less than 5 mins for me now, no memory problems.
Considering this fixed.
