### ISSUE TITLE
Messed up MANIFEST since 3.0.6

### ISSUE THREAD

**Issue by m1m** [cometd/cometd#772]
Since 3.0.6 cometd dosen't work in OSGI environment. Export/Import sections are messed up.
e.g. same import/export packages in bayeux-api
```
Export-Package = 
	org.cometd.bayeux;version=3.0.10,
	org.cometd.bayeux.server;uses:="org.cometd.bayeux,org.cometd.bayeux.client";version=3.0.10,
	org.cometd.bayeux.client;uses:=org.cometd.bayeux;version=3.0.10
Import-Package = 
	org.cometd.bayeux,
	org.cometd.bayeux.client
```

I noticed that there were Bnd tool version change between 3.0.5 and 3.0.6
`Tool = Bnd-2.4.1.201501161923` for 3.0.5
`Tool = Bnd-3.2.0.201605172007` for 3.0.6 and later

**Comment by sbordet** [comment]
When you say that it does not work, have you actually tried, or you are assuming based on the MANIFEST entries ?

I ask because the configuration of the `maven-bundle-plugin` used to generate the OSGi MANIFEST entries is similar to that of the Jetty project, and we know that Jetty works in OSGi.

The `maven-bundle-plugin` [documentation for the default behavior](http://felix.apache.org/documentation/subprojects/apache-felix-maven-bundle-plugin-bnd.html#default-behavior) of `Import-Package` says:
> Any exported packages are also imported by default, to ensure a consistent class space

I have doubts that the super-simple configuration we have for the `maven-bundle-plugin` generates by default broken MANIFEST entries, so I need a strong confirmation that this issue is real.

**Comment by m1m** [comment]
Sorry for confusion, my problems were caused by something else
