### ISSUE TITLE
Difference between /meta/disconnect and /meta/unsubscribe call of Bayeux

### ISSUE THREAD

**Issue by Pratibha24** [cometd/cometd#790]
Hi,

@sbordet
For the salesforce streaming we have used CometD Bayeux client and once we are done we just call the bayeux.disconnect() and stops the client. If we do not call the unsubscribe , is there any harm over here?

What exactly is the purpose of disconnect and unsubscribe here?

The other query is , i tried to send some random headers in the request while handshake request using Comet for Salesforce streaming, but it still it worked. Does it ignores the headers based on some condition?

Thanks,
Pratibha

**Comment by sbordet** [comment]
> once we are done we just call the bayeux.disconnect() and stops the client. If we do not call the unsubscribe , is there any harm over here?

No. The server will detect that the client is disconnected and remove the subscription metadata associated to that client.

 > What exactly is the purpose of disconnect and unsubscribe here?

The disconnect call disconnect the client completely from the server.

The unsubscribe call stops the client from receiving messages on the channel that was unsubscribed from. All other channels are still working as before, and the client can send messages to the server. 

> I tried to send some random headers in the request

Sending random headers to the server that does not know about them is likely to have no effect because the server will no look them up.

**Comment by Pratibha24** [comment]
Cool! Thanks a lot @sbordet .
You are always helpful and on the point. 

Regards,
Pratibha
