### ISSUE TITLE
In AbstractHttpTransport _sessions should be protected instead of private

### ISSUE THREAD

**Issue by andreifsolomon** [cometd/cometd#793]
Hi,

**Regarding cometd 3.1.4:**
When we extend **AbstractHttpTransport** we would like to have access to the **_sessions** class variable from the subclass. For instance, the **_logger** class variable is already allowing access to subclasses.

public abstract class AbstractHttpTransport extends AbstractServerTransport {
...
    **protected final Logger _logger = LoggerFactory.getLogger(getClass());**
    private final ThreadLocal<HttpServletRequest> _currentRequest = new ThreadLocal<>();
    **protected final Map<String, Collection<ServerSessionImpl>> _sessions = new HashMap<>();**_
    private final ConcurrentMap<String, AtomicInteger> _browserMap = new ConcurrentHashMap<>();
...

**Comment by sbordet** [comment]
Why? I'm not keen to make `_sessions` a `public` field.

**Comment by andreifsolomon** [comment]
Hi Simone,
It would help to have it protected, not public.

**Comment by sbordet** [comment]
You have not explained why yet.

**Comment by andreifsolomon** [comment]
For instance, if I want to override "**findCurrentSessions**" there is no way I can reference **_sessions** and use it part of my logic.

**Comment by sbordet** [comment]
You have explained what, not why.

Just because you continue to say "I want `_sessions` protected, I want to override `findCurrentSessions()`, I want ... I want ...` you are not going to convince me.

Produce a detailed use case, what you are actually trying to do, why the current situation is not enough for what you want to do, present the alternative you have to code if `_sessions` will remain private, and why you think making `_sessions` protected will help you.

**Comment by sbordet** [comment]
Closing - lack of activity.
