### ISSUE TITLE
CometD Long Polling takes longer than timeout value

### ISSUE THREAD

**Issue by jaypatel512** [cometd/cometd#837]
Hey all,

I have a timeout set for cometD long polling as 60000ms (60 seconds). And client is configured to have a socketTimeout as 62000ms (62 seconds). We are seeing socketTimeout in some cases, where our long polling client goes above 60000ms. Am I missing something here ? How can the socketTimeout be calculated to ensure we do not get a timeout via socket in normal cases.

**Comment by sbordet** [comment]
The server should always timeout at 60 seconds. The client may see more than that because of network roundtrips, so perhaps you have a really bad network?
Also, if the connection is dropped for any reason, the client may timeout because the server cannot write back to the client.

Do you have DEBUG logs that show this behavior?

**Comment by jaypatel512** [comment]
Unfortunately not, as this is seen in production only.

**Comment by sbordet** [comment]
Could be Full GC taking many seconds?

**Comment by jaypatel512** [comment]
I doubt that. Closing the issue as I do not have any pointers to give at this point. Will re-open or create a new one once I have more information for you. Thanks :)
