### ISSUE TITLE
It it possible for BayeuxClient to reconnect to another node on transport failure?

### ISSUE THREAD

**Issue by nathklei** [cometd/cometd#907]
Problem: I am running multiple cometd nodes in a clustered setup, using oort. Most of my clients are in front of a load balancer, as in the picture in https://docs.cometd.org/current/reference/#_typical_infrastructure

However, some clients are instead behind the load balancer, and I would like them to automatically reconnect to another node in the cluster should their current transport fail.

I see that `ClientTransport.FailureInfo` has a `url` field, but I do not see it set. It seems like there is some infrastructure in place to have that establish a new URL for the transport in the cometd codebase.

Absent figuring out how to get that working, I'm planning on overriding the onTransportFailure to set failureInfo.url to the next node in my cluster.

Is there an easier way to accomplish this?

Thanks!

**Comment by sbordet** [comment]
> It seems like there is some infrastructure in place to have that establish a new URL for the transport in the cometd codebase.

Correct, it was implemented in #483.
See an example [here](https://github.com/cometd/cometd/blob/4.0.6/cometd-java/cometd-java-tests/src/test/java/org/cometd/tests/TransportFailureTest.java#L224).

The idea is that if a client application sets the `FailureInfo.url` field, then CometD will honor its value and try to reconnect to that URL.

The client, however, has no idea of the new URL (different host? same host, different port? etc.), so this must be communicated to the client out-of-band (or be hardcoded).

For example, you may know that your CometD nodes have fixed IPs `1.2.3.4` and `1.2.3.5`, so you can hardcode them into the client application that overrides `onTrasportFailure()`.

Another example could be that, upon first handshake (with any node), the client receives a message with a list of the CometD node URLs (so each node in the cluster knows all the others).

Another example could be that the client application contacts a third party service (not even using CometD) to get the list of the CometD nodes.

Point being that communicating the list of CometD nodes to the client is not CometD business because it can be achieved in so many ways, so the applications need to write that code.

CometD helps in that it is sufficient for applications to set the `FailureInfo.url`, and CometD does all the rest.

Let know if you get this working and how, it would be a good reference of this feature. Thanks!

**Comment by nathklei** [comment]
Hey @sbordet thanks a lot, appreciate the quick reply. Seems my approach is the way to go - I've overloaded onTransportFailure and set the url and things do work as expected.

Regarding how my client specifically gets these URLs, unfortunately I won't be able to share any of the actual code, but I've essentially extended BayeuxClient as in your example, providing a

`Supplier<List<String>> urls` param as an argument, that supplies the snapshot of the URLs my client knows about which is provided by some other infrastructure.

For initial connection, I take the first URL from the list, then on transport failure I take the next available in the list, accounting for any resizes of the backing list accordingly. The result is I end up cycling through the nodes.

**Comment by sbordet** [comment]
@nathklei thanks for the feedback. Feel free to close the issue if it's solved for you.

**Comment by nathklei** [comment]
Thanks!
